"""create feature_snapshot table

Revision ID: f002b1cd86f2
Revises:
Create Date: 2026-06-27 03:37:46.793088

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "f002b1cd86f2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "featuresnapshot",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("entity_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("total_purchases", sa.Integer(), nullable=False),
        sa.Column("total_spend", sa.Float(), nullable=False),
        sa.Column("avg_order_value", sa.Float(), nullable=False),
        sa.Column("num_logins_7d", sa.Integer(), nullable=False),
        sa.Column("num_logins_30d", sa.Integer(), nullable=False),
        sa.Column("days_since_last_login", sa.Integer(), nullable=False),
        sa.Column("days_since_last_purchase", sa.Integer(), nullable=False),
        sa.Column("account_age_days", sa.Integer(), nullable=False),
        sa.Column("computed_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_featuresnapshot_entity_id"),
        "featuresnapshot",
        ["entity_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_featuresnapshot_entity_id"), table_name="featuresnapshot")
    op.drop_table("featuresnapshot")
    # ### end Alembic commands ###
